#!/bin/bash

scp ./server_lifecycle_manager/agent.py orion@10.1.37.28:~/data/ias_nfs/system
scp ./server_runtime/inference_server.py orion@10.1.37.28:~/data/ias_nfs/system
scp ./server_runtime/webapp_server.py orion@10.1.37.28:~/data/ias_nfs/system

